[package]
name = "mmcp-auth"
description = "Authentication and authorization for mmcp: Argon2, PASETO, axum-login glue"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
mmcp-core = { workspace = true }
mmcp-db = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
argon2 = { workspace = true }
rusty_paseto = { workspace = true }
serde_json = "1"
jiff = { workspace = true }
axum-login = { workspace = true }
sea-orm = { workspace = true }
tokio = { workspace = true }
webauthn-rs = { workspace = true }

[lints]
workspace = true
