//! Client subcommands.

pub mod archive_filter;
pub mod bootstrap;
pub mod claude;
pub mod debug;
pub mod export;
pub mod feature;
pub mod group;
pub mod health;
pub mod hook;
pub mod import;
pub mod init;
pub mod issue;
pub mod memory;
pub mod milestone;
pub mod serve;
pub mod status;
pub mod subscribe;
pub mod subscription;
pub mod sync;
pub mod tools;
pub mod tracker_cli;
